# Generated by Django 4.2.2 on 2023-07-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('image', models.URLField()),
            ],
        ),
    ]
